PGMActas_V2/Models/Automotor.cs
using PGMActas_V2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.Models
{
    public class Automotor
    {
        public int id_automotor { get; set; }
        public string numero_dominio { get; set; }
        public int id_marca_tipo_vehiculo { get; set; }
        public string modelo { get; set; }
        public string color { get; set; }
        public MarcaItemVM marca { get; set; }
        public TipoVehiculoItemVM tipoVehiculo { get; set; }
        public List<Persona> listadoTitulares { get; set; }

        public Automotor(int id_automotor, string numero_dominio, int id_marca_tipo_vehiculo, string modelo, string color)
        {
            this.id_automotor = id_automotor;
            this.numero_dominio = numero_dominio;
            this.id_marca_tipo_vehiculo = id_marca_tipo_vehiculo;
            this.modelo = modelo;
            this.color = color;
        }

        public Automotor()
        {
        }
    }

}

PGMActas_V2/Models/Infraccion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.Models
{
    public class Infraccion
    {
        public int codigo_infraccion { get; set; }
        public string nomenclatura { get; set; }
        public string descripcion { get; set; }
        public bool estado { get; set; }
        public string calificacion { get; set; }
        public double? monto_unitario { get; set; }
        public Normativa normativa { get; set; }
        public Articulo articulo { get; set; }
        public GrupoInfraccion grupoInfracciones { get; set; }
        public bool habilitado_retuvo_licencia { get; set; }
        public bool habilitado_retuvo_vehiculo { get; set; }    

    }
}

PGMActas_V2/Models/InfraccionForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.Models
{
    public class InfraccionForm
    {
        public string form_codigo_infraccion { get; set; }
    }
}

PGMActas_V2/Models/Inspector.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.Models
{
    public class Inspector
    {
        public int id_inspector { get; set; }
        public bool habilitado { get; set; }
        public Persona persona { get; set; } = new Persona();
        public string matricula { get; set; }
        public int rango_comienzo_acta { get; set; }
        public int rango_fin_acta { get; set; }
    }
}

PGMActas_V2/Models/Ordenanza.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.Models
{
    public class Ordenanza
    {
        private string estadoN = "";
        public int codigo_ordenanza { get; set; }
        public string nomenclatura { get; set; }
        public string descripcion { get; set; }
        public bool estado { get; set; }
        public string calificacion { get; set; }

    }
}

PGMActas_V2/Models/Persona.cs
using PGMActas_V2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.Models
{
    public class Persona
    {
        public int id_persona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string numero_documento { get; set; }
        public string direccion { get; set; }
        public int codigo_postal { get; set; }
        public TipoDocumentoItemVM tipoDocumento { get; set; }
        public LocalidadItemVM localidad { get; set; }
        public int idResponsabilidadLegal { get; set; }
        public bool infractor { get; set; }
        public bool variasResp { get; set; } = false;
        public List<int> resposabilidadesLegales { get; set; }
    }
}

PGMActas_V2/Models/PersonaForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.Models
{
    public class PersonaForm
    {
        public string form_apellido { get; set; }
        public string form_id_persona { get; set; }
        public string form_nombre { get; set; }
        public string form_numero_documento { get; set; }
        public string form_tipo_documento { get; set; }
        public string form_localidad { get; set; }
        public string form_domicilio { get; set; }
        public string form_codigo_postal { get; set; }
        public string form_responsabilidad { get; set; }
    }
}

PGMActas_V2/ViewModels/InfraccionesPersonaParticular.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMActas_V2.ViewModels
{
    public class InfraccionesPersonaParticular
    {
        public int numero_acta { get; set; }
        public string fecha_acta { get; set; }
        public string direccion { get; set; }
        public string observaciones { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int codigo_infraccion { get; set; }
        public string responsabilidad_legal { get; set; }
    }
}

PGMActas_V2/Controllers/ActaController.cs
using PGMActas_V2.DataAccess;
using PGMActas_V2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PGMActas_V2.Models;

namespace PGMActas_V2.Controllers
{
    public class ActaController : Controller
    {

        [HttpGet]
        public ActionResult CargarActa()
        {
            //combo Marcas
            List<MarcaItemVM> listaMarcas = AutomotorDA.obtenerListaMarcas();
            ViewBag.items = listaMarcas;
            //combo Tipos Vehiculos
            List<TipoVehiculoItemVM> listaTiposVehiculos = AutomotorDA.obtenerListaTiposVehiculos();
            ViewBag.items2 = listaTiposVehiculos;
            //combo Tipos Documentos
            List<TipoDocumentoItemVM> listaTiposDocumentos = PersonaDA.obtenerTiposDocumentos();
            ViewBag.items3 = listaTiposDocumentos;
            //combo Paises
            List<PaisItemVM> listaPaises = PersonaDA.obtenerPaises();
            ViewBag.items4 = listaPaises;
            //combo Provincias
            List<ProvinciaItemVM> listaProvincias = PersonaDA.obtenerProvincias();
            ViewBag.items5 = listaProvincias;
            //combo Localidades
            List<LocalidadItemVM> listaLocalidades = PersonaDA.obtenerLocalidades();
            ViewBag.items6 = listaLocalidades;
            //combo Responsabilidad Legal
            List<ResponsabilidadLegalItemVM> listaResponsabilidadesLegales = PersonaDA.obtenerResponsabilidadesLegales();
            listaResponsabilidadesLegales.RemoveAt(0);//borro titular del combobox
            ViewBag.items7 = listaResponsabilidadesLegales;
            //
            return View();
        }

         [HttpGet]
         public ActionResult ActaCargada(int numero_acta)
          {
            ViewBag.numero_acta = numero_acta;
              return View();
          }


        //Vista Parciales de Infracciones
        [HttpGet]
        public PartialViewResult Infraccion()
        {

            return PartialView("_Infraccion");
        }

        [HttpGet]
        public PartialViewResult InfraccionesResultado()
        {

            List<Infraccion> listaInfracciones = InfraccionDA.obtenerListaInfracciones();
            return PartialView("_InfraccionesResultado", listaInfracciones);
        }

        [HttpPost]
        public PartialViewResult InfraccionesResultado(string searchString = "")
        {

            List<Infraccion> listaInfracciones = InfraccionDA.obtenerListaInfracciones();
            if (!String.IsNullOrEmpty(searchString))
            {
                //  listaInfracciones = listaInfracciones.Where(s => s.nomenclatura.Contains(searchString)).ToList();
                listaInfracciones = listaInfracciones.Where(s => s.nomenclatura.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1 ||
                s.descripcion.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1 ||
                s.grupoInfracciones.grupo.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1 ||
                s.calificacion.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1

                ).ToList();
            }



            return PartialView("_InfraccionesResultado", listaInfracciones);
        }

        //Vistas Parciales Inspectores

        [HttpGet]
        public PartialViewResult Inspector()
        {

            return PartialView("_Inspector");
        }

        [HttpGet]
        public PartialViewResult InspectoresResultado()
        {

            List<Inspector> listaInspectores = InspectorDA.obtenerListaInspectores();
            return PartialView("_InspectoresResultado", listaInspectores);
        }

        [HttpPost]
        public PartialViewResult InspectoresResultado(string searchString = "")
        {

            List<Inspector> listaInspectores = InspectorDA.obtenerListaInspectores();
            if (!String.IsNullOrEmpty(searchString))
            {
                listaInspectores = listaInspectores.Where(s => (s.persona.nombre.ToLower().Contains(searchString.ToLower()) || s.persona.apellido.ToLower().Contains(searchString.ToLower()) ||
                (s.persona.nombre.ToLower()+" " + s.persona.apellido.ToLower()).Contains(searchString.ToLower()) ||
                s.matricula.ToString().Contains(searchString)
                )).ToList();

            }
            return PartialView("_InspectoresResultado", listaInspectores);
        }

        //Vistas Parciales Automotores

        [HttpGet]
        public PartialViewResult Automotor()
        {

            return PartialView("_Automotor");
        }

        [HttpGet]
        public PartialViewResult AutomotoresResultado()
        {

            List<Automotor> listaAutomotores = AutomotorDA.obtenerListaAutomotores();
            return PartialView("_AutomotoresResultado", listaAutomotores);
        }

        [HttpPost]
        public PartialViewResult AutomotoresResultado(string searchString = "")
        {

            List<Automotor> listaAutomotores = AutomotorDA.obtenerListaAutomotores();
            if (!String.IsNullOrEmpty(searchString))
            {

                listaAutomotores = listaAutomotores.Where(s => s.numero_dominio.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1 ||
                s.tipoVehiculo.tipo_vehiculo.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1 ||
                s.marca.marca.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1 ||
                s.modelo.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) != -1

                ).ToList();
            }
            return PartialView("_AutomotoresResultado", listaAutomotores);
        }



        //Vistas Parciales Personas

        [HttpGet]
        public PartialViewResult Persona()
        {

            return PartialView("_Persona");
        }

        [HttpGet]
        public PartialViewResult PersonasResultado()
        {

            List<Persona> listaPersonas = PersonaDA.obtenerListaPersonas();
            return PartialView("_PersonasResultado", listaPersonas);
        }

        [HttpPost]
        public PartialViewResult PersonasResultado(string searchString = "")
        {

            List<Persona> listaPersonas = PersonaDA.obtenerListaPersonas();
            if (!String.IsNullOrEmpty(searchString))
            {
                /*  int nroDoc;

                  bool success = Int32.TryParse(searchString, out nroDoc);
                  listaPersonas = listaPersonas.Where(s => s.numero_documento == nroDoc).ToList();
                */
                listaPersonas = listaPersonas.Where(s => s.numero_documento.ToString().Contains(searchString) ||
               s.nombre.ToLower().Contains(searchString.ToLower()) || s.apellido.ToLower().Contains(searchString.ToLower()) ||
                (s.nombre.ToLower() + " " + s.apellido.ToLower()).Contains(searchString.ToLower())
                ).ToList();
            }
            return PartialView("_PersonasResultado", listaPersonas);
        }

        //verificar numero acta repetido
        public HtmlString verificarNumeroActa(int numero_acta)
        {

            var success = ActaDA.obtenerNumeroActa(numero_acta);
            var mensaje = success ? "Acta "+ numero_acta +" ya existente, para consultarla ingrese <a href=''>aquí</a>":"Número de acta válido.";
            var response = new { success = success, Message = mensaje };
            System.Web.Script.Serialization.JavaScriptSerializer jSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            return new HtmlString(jSerializer.Serialize(response));
        }

        //verificar numero acta rango inspector
        public HtmlString verificarNumeroActaRangoInspector(int id_inspector, int numero_acta)
        {
            var success = false;
            var rangoComienzo = InspectorDA.obtenerRangoComienzoInspector(id_inspector);
            var rangoFin = InspectorDA.obtenerRangoFinInspector(id_inspector);
            if ((numero_acta >= rangoComienzo) && (numero_acta<=rangoFin))
            {
                success = true;
            }

            var mensaje = success ? "Acta dentro del rango del inspector. ":"Acta "+ numero_acta+ " fuera del rango del inspector.";
            var response = new { success = success, Message = mensaje };
            System.Web.Script.Serialization.JavaScriptSerializer jSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            return new HtmlString(jSerializer.Serialize(response));
        }


        //Partial view de las infracciones de una persona particular
        [HttpGet]
        public PartialViewResult InfraccionesPersonaParticular(int id_persona)
        {

            List<InfraccionesPersonaParticular> listaActasPersonaParticular = ActaDA.obtenerListaActasPersonaParticular(id_persona).OrderBy(o => o.responsabilidad_legal).ToList();

           
            if (listaActasPersonaParticular.Count()>0)
            {
                var persona = listaActasPersonaParticular.FirstOrDefault();
                ViewBag.Nombre = "Actas de " + persona.nombre + ' ' + persona.apellido;
            }
            else
            {
                ViewBag.Nombre = "La persona seleccionada no tiene actas.";
            }
           
  
            return PartialView("_InfraccionesPersonaParticular", listaActasPersonaParticular);
        }
    }
}

PGMActas_V2/Controllers/AutomotorController.cs
using Newtonsoft.Json;
using PGMActas_V2.DataAccess;
using PGMActas_V2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PGMActas_V2.Controllers
{
    public class AutomotorController : Controller
    {
        // GET: Automotor
        public ActionResult Index()
        {
            return View();
        }

        public HtmlString ObtenerDetallesAutomotor(int idAutomotor)
        {
            List<Automotor> listaAutomotores = AutomotorDA.obtenerListaAutomotores();
            var automotor = listaAutomotores.Where(x => x.id_automotor == idAutomotor).FirstOrDefault();
            System.Web.Script.Serialization.JavaScriptSerializer jSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            return new HtmlString(jSerializer.Serialize(automotor));
        }

        //verificar numero de dominio repetido
        public HtmlString verificarNumeroDominio(string numeroDominio, string numeroDominioOriginal)
        {

            var success = AutomotorDA.obtenerNumeroDominio(numeroDominio);
            var mensaje = success ? "Número de dominio "+ numeroDominioOriginal + " ya existente." : "Número de dominio válido.";
            var response = new { success = success, Message = mensaje };
            System.Web.Script.Serialization.JavaScriptSerializer jSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            return new HtmlString(jSerializer.Serialize(response));


        }

    }
}

PGMActas_V2/Controllers/PersonaController.cs
using PGMActas_V2.DataAccess;
using PGMActas_V2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PGMActas_V2.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            return View();
        }

        public HtmlString ObtenerDetallesPersona(string numeroDocumento)
        {
            List<Persona> listaPersonas = PersonaDA.obtenerListaPersonas();
            var persona = listaPersonas.Where(x => x.numero_documento == numeroDocumento).FirstOrDefault();
            System.Web.Script.Serialization.JavaScriptSerializer jSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            return new HtmlString(jSerializer.Serialize(persona));
        }

        //verificar numero de documento repetido
        public HtmlString verificarNumeroDocumento(string numeroDocumento)
        {

            var success = PersonaDA.obtenerNumeroDocumento(numeroDocumento);
            var mensaje = success ? "Número de documento "+ numeroDocumento +" ya existente." : "Número de documento válido.";
            var response = new { success = success, Message = mensaje };
            System.Web.Script.Serialization.JavaScriptSerializer jSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            return new HtmlString(jSerializer.Serialize(response));


        }

    }
}

PGMActas_V2/Views/Shared/_Automotor.cshtml
@{
    ViewBag.Title = "_Automotor";
}


@using (Ajax.BeginForm("AutomotoresResultado", "Acta", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST",
    UpdateTargetId = "tablaAutomotores"

}))
{
    <p>
        Buscar por número de dominio, tipo de vehículo, marca o modelo: @Html.TextBox("searchString", null, new { maxlength = 50, onkeypress = "return noAlfanumericos(event)" })
        <input type="submit" id="search" class="btn btn-success btn-xs" value="Buscar" />
    </p>
}


<div id="tablaAutomotores">
</div>

PGMActas_V2/Views/Shared/_AutomotoresResultado.cshtml
@model IEnumerable<PGMActas_V2.Models.Automotor>
@{
    ViewBag.Title = "_AutomotoresResultado";
}


<div style="display:grid">
    <table>
        <thead>
            <tr class="table100-head" style="border-bottom: 2px solid #4caf50">
                <th class="column1" style="padding: 0.3rem"> Nro Dominio </th>
                <th class="column2" style="padding: 0.3rem"> Tipo vehículo </th>
                <th class="column3" style="padding: 0.3rem"> Marca </th>
                <th class="column3" style="padding: 0.3rem"> Modelo </th>
                <th class="column3" style="padding: 0.3rem"> Color </th>
                <th class="column5" style="padding: 0.3rem"> Seleccionar </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var automotor in Model)
            {
                <tr>
                    <td>@automotor.numero_dominio</td>
                    <td>@automotor.tipoVehiculo.tipo_vehiculo</td>
                    <td>@automotor.marca.marca</td>
                    <td>@automotor.modelo</td>
                    <td>@automotor.color</td>
                    <td>

                        <button class="btn btn-success btn-xs visualizarDetalle" id="@automotor.id_automotor">
                            Llenar
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('button.visualizarDetalle').click(function () {
            var idAutomotor = $(this).attr('id');
           //$.get(URL,data,function(data,status,xhr),dataType)
           $.get(
                "@Url.Action("ObtenerDetallesAutomotor","Automotor")",
               { idAutomotor: idAutomotor},
               function (response) {
                   limpiarTitulares();
                   registerTitulares(response);
                },
                "json"
            );

            $('#modalAutomotor').modal('toggle');

        });
        //Función de limpiar botón
        $('#btnAutomotorLimpiar').click(function () {
            limpiarTitulares();
        });
        $("#listadoTitulares").on("click", "div", function (event) {
            $('#modalPersonaUnitaria').modal('toggle');

        });

  
    });




</script>

PGMActas_V2/Views/Shared/_Infraccion.cshtml
@{
    ViewBag.Title = "_Infraccion";
}

@using (Ajax.BeginForm("InfraccionesResultado", "Acta", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST",
    UpdateTargetId = "tablaInfraccion"//,

}))
{
<p>
    Buscar nomenclatura, descripción, clasificación o calificación: @Html.TextBox("searchString", null, new { maxlength = 80, onkeypress = "return validacionCampoObservaciones(event)" })
    <input type="submit" id="search" class="btn btn-success btn-xs" value="Buscar" />
</p>
}


<div id="tablaInfraccion">
</div>

PGMActas_V2/Views/Shared/_InfraccionesPersonaParticular.cshtml
@model IEnumerable<PGMActas_V2.ViewModels.InfraccionesPersonaParticular>
@{
   
}



<div style="display:grid">
    <h5> @ViewBag.Nombre</h5>    
    <table>
        <thead>
            <tr class="table100-head" style="border-bottom: 2px solid #4caf50">
                <th class="column1" style="padding: 0.3rem"> Nro Acta </th>
                <th class="column2" style="padding: 0.3rem"> Fecha Acta </th>
                <th class="column3" style="padding: 0.3rem"> Responsabilidad Legal </th>
                <th class="column3" style="padding: 0.3rem"> Código de Infracción </th>
                <th class="column3" style="padding: 0.3rem"> Observaciones </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var acta in Model)
            {
            <tr>
                <td>@acta.numero_acta</td>
                <td>@acta.fecha_acta</td>
                <td>@acta.responsabilidad_legal</td>
                <td>@acta.codigo_infraccion</td>
                <td>@acta.observaciones</td>
            </tr>
            }
        </tbody>
    </table>
</div>

PGMActas_V2/Views/Shared/_Inspector.cshtml
@{
    ViewBag.Title = "_Inspector";
}

@using (Ajax.BeginForm("InspectoresResultado", "Acta", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST",
    UpdateTargetId = "tablaInspectores"

}))
{
    <p>
        Buscar por nombre y/o apellido o matrícula: @Html.TextBox("searchString", null, new { maxlength = 70, onkeypress = "return noAlfanumericos(event)"})
        <input type="submit" id="search" class="btn btn-success btn-xs" value="Buscar" />
    </p>
}


<div id="tablaInspectores">
</div>

PGMActas_V2/Views/Shared/_Ordenanza.cshtml
@{
    ViewBag.Title = "_Ordenanza";
}

@using (Ajax.BeginForm("OrdenanzasResultado", "Acta", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace, 
    HttpMethod = "POST",
    UpdateTargetId = "tablaOrdenanzas"//,
                                 
}))
{
<p>
    Buscar por código, nomenclatura o descripción: @Html.TextBox("searchString")
    <input type="submit" id="search" class="btn btn-success btn-xs" value="Buscar" />
</p>
}


<div id="tablaOrdenanzas">
</div>

PGMActas_V2/Views/Shared/_Persona.cshtml
@{
    ViewBag.Title = "_Persona";
}

@using (Ajax.BeginForm("PersonasResultado", "Acta", new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST",
    UpdateTargetId = "tablaPersona"

}))
{
    <p>
        Buscar por nombre y/o apellido o número de documento : @Html.TextBox("searchString", null, new { maxlength = 70, onkeypress = "return noAlfanumericos(event)" })
        <input type="submit" id="search" class="btn btn-success btn-xs" value="Buscar" />
    </p>
}


<div id="tablaPersona">
</div>

PGMActas_V2/Views/Shared/_PersonasResultado.cshtml
@model IEnumerable<PGMActas_V2.Models.Persona>

@{
    ViewBag.Title = "_PersonasResultado";
}

<div style="display:grid">
    <table>
        <thead>
            <tr class="table100-head" style="border-bottom: 2px solid #4caf50">
                <th class="column1" style="padding: 0.3rem"> Tipo Documento </th>
                <th class="column2" style="padding: 0.3rem"> Nro Documento </th>
                <th class="column3" style="padding: 0.3rem"> Nombre </th>
                <th class="column5" style="padding: 0.3rem"> Seleccionar </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var persona in Model)
            {
                <tr>
                    <td> @persona.tipoDocumento.tipo_documento </td>
                    <td> @persona.numero_documento </td>
                    <td> @persona.nombre @persona.apellido </td>
                    <td>
                        <button class="btn btn-success btn-xs agregarP" id="@persona.numero_documento">
                            Llenar
                        </button>
                    </td>
                </tr>
            }


        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        $('button.agregarP').click(function () {
            var controlBtn = $('#btnBuscarPersona').val();
            //persona titular
            if (controlBtn == 0) {
                var numeroDocumento = $(this).attr('id');
                $("#personaID").attr("value", numeroDocumento);
                $("#personaID").val(numeroDocumento);
                 $.get(
                    "@Url.Action("ObtenerDetallesPersona","Persona")",
                     { numeroDocumento: numeroDocumento},
                     function (response) {
                         console.log("Obtener detalles persona");
                         console.log(response);
                              var idPersona = response.id_persona;
                              var numeroDocumento = response.numero_documento;
                              var tipoDocumento = response.tipoDocumento.id_tipo_documento;
                              var nombre = response.nombre;
                              var apellido = response.apellido;

                              $("#personaIDPosible").val(idPersona);
                              $("#personaID").val(numeroDocumento);
                              $("#tipoDoc").val(tipoDocumento);
                              $("#nombrePersona").val(nombre);
                              $("#apellidoPersona").val(apellido);
                     },
                     "json"
                 );
            }
            //persona infractor
            else {
                var numeroDocumento = $(this).attr('id');
                $("#personaInfID").attr("value", numeroDocumento);
                $("#personaInfID").val(numeroDocumento);

                $.get(
                    "@Url.Action("ObtenerDetallesPersona","Persona")",
                     { numeroDocumento: numeroDocumento},
                    function (response) {
                        console.log("Obtener detalles persona");
                        console.log(response);
                        var idPersona = response.id_persona;
                        var numeroDocumento = response.numero_documento;
                        var tipoDocumento = response.tipoDocumento.id_tipo_documento;
                        var nombre = response.nombre;
                        var apellido = response.apellido;
                        var localidad = response.localidad.id_localidad;
                        var provincia = response.localidad.provincia.id_provincia;
                        var pais = response.localidad.provincia.pais.id_pais;
                        var domicilio = response.direccion;
                        var codigoPostal = response.codigo_postal;
                        console.log(localidad);
                        $("#personaIDPosibleInf").val(idPersona);
                        $("#personaInfID").val(numeroDocumento);
                        $("#tipoDocInf").val(tipoDocumento);
                        $("#nombreInfID").val(nombre);
                        $("#apellidoInfID").val(apellido);
                        $("#paisInfID").val(pais);
                        $("#provinciaInfID").val(provincia);
                        $("#localidadInfractorID").val(localidad);
                        $("#domicilioInfID").val(domicilio);
                        $("#codigoPostalID").val(codigoPostal);
                        //$("#comboResponsabilidadLegal").val('2');
                        
                     },
                     "json"
                 );
            }
            $('#modalPersona').modal('toggle');
        })

        
    });

</script>